name: Setup Docker Builder
author: Blacksmith
description: Sets up a Docker buildkitd builder with sticky disk cache for improved build performance
branding:
  icon: layers
  color: black
inputs:
  buildx-version:
    description: Buildx version. (e.g., v0.23.0, latest)
    required: false
    default: v0.23.0
  platforms:
    description: "List of target platforms for build (e.g., linux/amd64,linux/arm64,linux/arm/v7)"
    required: false
  nofallback:
    description: "If true, fail the action if Blacksmith builder setup fails instead of falling back to local builder"
    required: false
    default: "false"
  github-token:
    description: "GitHub token for GitHub API access"
    required: false
  buildkit-version:
    description: "BuildKit version to install (e.g., v0.16.0, v0.18.0). If not specified, uses system default"
    required: false
runs:
  using: node20
  main: dist/index.js
  post: dist/index.js
