name: Lint

on:
  pull_request:
  push:
    branches: [main]

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - uses: pnpm/action-setup@v4
        with:
          version: 8

      - uses: bufbuild/buf-setup-action@v1
        with:
          github_token: ${{ github.token }}

      - name: Configure npm for buf registry
        env:
          BUF_TOKEN: ${{ secrets.BUF_TOKEN }}
        run: |
          npm config set @buf:registry https://buf.build/gen/npm/v1/
          npm config set //buf.build/gen/npm/v1/:_authToken $BUF_TOKEN

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v4
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install

      - name: Check formatting
        run: pnpm run format

      - name: Lint TypeScript
        run: pnpm run lint || true # Allow failures for now, will fix in follow-up

      - name: Type check
        run: pnpm tsc --noEmit || true # Allow failures for now
