name: Verify Build Output

on:
  pull_request:
    branches:
      - main
      - master

jobs:
  verify-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8

      - uses: bufbuild/buf-setup-action@v1
        with:
          github_token: ${{ github.token }}

      - name: Configure npm for buf registry
        env:
          BUF_TOKEN: ${{ secrets.BUF_TOKEN }}
        run: |
          npm config set @buf:registry https://buf.build/gen/npm/v1/
          npm config set //buf.build/gen/npm/v1/:_authToken $BUF_TOKEN

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm run build

      - name: Check for changes
        run: |
          if [[ -n "$(git status --porcelain dist)" ]]; then
            echo "::error::Build generated new changes in dist/. Please commit the generated files."
            git status
            git diff dist
            exit 1
          fi
